### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by netojose** [sthrohan400/easy-react-admin-boilerplate#1]
How to install this, if the project owner added package.json file to .gitignore, and the repository hasn't this file?

**Comment by sthrohan400** [comment]
Missing package.json has been added to the project.
[https://github.com/sthrohan400/easy-react-admin-boilerplate/commit/0674411786fd1380f807424d333e6ae5fa74fd91](url)

**Comment by netojose** [comment]
Thanks, @sthrohan400 !!!
